package algorithms.heuristics;

/**
 * Created by gvoiron on 09/01/17.
 * Time : 15:09
 */
public enum EEUAComputerHeuristics {

    EXCLUSIVE,
    EXHAUSTIVE,
    OLD_EXCLUSIVE,
    OLD_EXHAUSTIVE,
    NO_ORDERING_NO_COLORATION,
    ORDERING_NO_COLORATION,
    NO_ORDERING_COLORATION,
    ORDERING_NO_COLORATION_EXCLUSIVE, NO_RELEVANCE, RELEVANCE, ORDERING_COLORATION

}
